### ISSUE TITLE
Unable to run deno_bindgen

### ISSUE THREAD

**Issue by xxSkyy** [denoland/deno_bindgen#83]
I'm unable to run deno_bindgen always throwing following error

```
error: Uncaught (in promise) NotFound: No such file or directory (os error 2), remove 'bindings.json'
await build().catch((_) => Deno.removeSync("bindings.json"));
                                ^
    at Object.opSync (deno:core/01_core.js:170:12)
    at Object.removeSync (deno:runtime/js/30_fs.js:150:10)
    at https://deno.land/x/deno_bindgen@0.5.1/cli.ts:56:33
    at async https://deno.land/x/deno_bindgen@0.5.1/cli.ts:56:1
```

To be sure that's not my mistake I've even tried running `deno_bindgen` command in example directory, same thing.

`OS`: `Manjaro 21.3.3`
`deno --version`:
```
deno 1.23.4 (release, x86_64-unknown-linux-gnu)
v8 10.4.132.8
typescript 4.7.4
```

**Comment by xxSkyy** [comment]
Solved. 
If anyone will face same issue 
**dont ever use snap** - so far it only gave me problems, with `VSCode` with `Deno` 
best way install just deno from install script
