### ISSUE TITLE
Doesn't work with Deno v1.25.0

### ISSUE THREAD

**Issue by skanehira** [denoland/deno_bindgen#90]
deno_bindgen doesn't work cause https://github.com/denoland/deno/pull/15518

<details><summary>log</summary><div>

```sh
$ deno test -A --unstable
Check file:///Users/skanehira/dev/github.com/denoland/deno_bindgen/example/bindings_test.ts
error: TS2345 [ERROR]: Argument of type 'Uint8Array' is not assignable to parameter of type 'ToNativeType<"usize" | "pointer">'.
  let rawResult = _lib.symbols.add2(a0_buf, a0_buf.byteLength)
                                    ~~~~~~
    at file:///Users/skanehira/dev/github.com/denoland/deno_bindgen/example/bindings/bindings.ts:173:37

TS2345 [ERROR]: Argument of type 'Uint8Array' is not assignable to parameter of type 'ToNativeType<"usize" | "pointer">'.
  let rawResult = _lib.symbols.test_buf(a0_buf, a0_buf.byteLength)
                                        ~~~~~~
    at file:///Users/skanehira/dev/github.com/denoland/deno_bindgen/example/bindings/bindings.ts:184:41

TS2345 [ERROR]: Argument of type 'Uint8Array' is not assignable to parameter of type 'ToNativeType<"usize" | "pointer">'.
  let rawResult = _lib.symbols.test_buffer_return(a0_buf, a0_buf.byteLength)
                                                  ~~~~~~
    at file:///Users/skanehira/dev/github.com/denoland/deno_bindgen/example/bindings/bindings.ts:190:51

TS2345 [ERROR]: Argument of type 'Uint8Array' is not assignable to parameter of type 'ToNativeType<"usize" | "pointer">'.
    a0_buf,
    ~~~~~~
    at file:///Users/skanehira/dev/github.com/denoland/deno_bindgen/example/bindings/bindings.ts:197:5

TS2345 [ERROR]: Argument of type 'Uint8Array' is not assignable to parameter of type 'ToNativeType<"usize" | "pointer">'.
  let rawResult = _lib.symbols.test_lifetime(a0_buf, a0_buf.byteLength)
                                             ~~~~~~
    at file:///Users/skanehira/dev/github.com/denoland/deno_bindgen/example/bindings/bindings.ts:210:46

TS2345 [ERROR]: Argument of type 'Uint8Array' is not assignable to parameter of type 'ToNativeType<"usize" | "isize" | "pointer">'.
  let rawResult = _lib.symbols.test_mixed(a0, a1_buf, a1_buf.byteLength)
                                              ~~~~~~
    at file:///Users/skanehira/dev/github.com/denoland/deno_bindgen/example/bindings/bindings.ts:226:47

TS2345 [ERROR]: Argument of type 'Uint8Array' is not assignable to parameter of type 'ToNativeType<"i32" | "usize" | "pointer">'.
    a1_buf,
    ~~~~~~
    at file:///Users/skanehira/dev/github.com/denoland/deno_bindgen/example/bindings/bindings.ts:234:5

TS2345 [ERROR]: Argument of type 'Uint8Array' is not assignable to parameter of type 'ToNativeType<"usize" | "pointer">'.
  let rawResult = _lib.symbols.test_mut_buf(a0_buf, a0_buf.byteLength)
                                            ~~~~~~
    at file:///Users/skanehira/dev/github.com/denoland/deno_bindgen/example/bindings/bindings.ts:243:45

TS2345 [ERROR]: Argument of type 'Uint8Array' is not assignable to parameter of type 'ToNativeType<"usize" | "pointer">'.
  let rawResult = _lib.symbols.test_serde(a0_buf, a0_buf.byteLength)
                                          ~~~~~~
    at file:///Users/skanehira/dev/github.com/denoland/deno_bindgen/example/bindings/bindings.ts:264:43

TS2345 [ERROR]: Argument of type 'Uint8Array' is not assignable to parameter of type 'ToNativeType<"usize" | "pointer">'.
  let rawResult = _lib.symbols.test_str(a0_buf, a0_buf.byteLength)
                                        ~~~~~~
    at file:///Users/skanehira/dev/github.com/denoland/deno_bindgen/example/bindings/bindings.ts:270:41

TS2345 [ERROR]: Argument of type 'Uint8Array' is not assignable to parameter of type 'ToNativeType<"usize" | "pointer">'.
  let rawResult = _lib.symbols.test_tag_and_content(a0_buf, a0_buf.byteLength)
                                                    ~~~~~~
    at file:///Users/skanehira/dev/github.com/denoland/deno_bindgen/example/bindings/bindings.ts:281:53

Found 11 errors.
```

</div></details>

**Comment by skanehira** [comment]
I'll fix this

**Comment by skanehira** [comment]
PR was already there.
https://github.com/denoland/deno_bindgen/pull/87

**Comment by skanehira** [comment]
https://github.com/denoland/deno_bindgen/pull/87 is complete.
